[package]
name = "super_tar"
version = "0.1.0"
authors = ["millsky <kyle83567@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.26"
flate2 = "1.0.13"
